### ISSUE TITLE
Document 01: Outside columns are treated as notes

### ISSUE THREAD

**Issue by anermina** [metanorma/mn-samples-plateau#105]
Specification: outside columns are treated as notes → likely ADOC modification Pattern C​

![image](https://github.com/user-attachments/assets/8d96827b-f608-40b9-a41d-7410fe6ad935)

_18th comment from Plateau team_

**Comment by ronaldtse** [comment]
Superseded and addressed by:
* https://github.com/metanorma/metanorma-plateau/issues/72
