### ISSUE TITLE
Document 01: Remove numbering of math blocks

### ISSUE THREAD

**Issue by anermina** [metanorma/mn-samples-plateau#108]
Specification: with numbers in parentheses ( ) → likely ADOC modification Pattern C

![image](https://github.com/user-attachments/assets/b625801b-4a24-45cf-bf56-dce60de72959)

![image](https://github.com/user-attachments/assets/c8c9374c-9efb-4d8f-bc12-ff45ab7769ae)

_28th and 29th comment from Plateau team_

**Comment by ronaldtse** [comment]
Closed.
