### ISSUE TITLE
Document 01: Fix part of the table that is treated as a note

### ISSUE THREAD

**Issue by anermina** [metanorma/mn-samples-plateau#109]
Specification: treated as a note → ADOC modification may be possible Pattern C​

![image](https://github.com/user-attachments/assets/f3cf8a1d-e47b-4877-a2bf-bea2defb137b)

_30th comment from Plateau team_

**Comment by ronaldtse** [comment]
Superseded and addressed by:
* https://github.com/metanorma/metanorma-plateau/issues/72
