### ISSUE TITLE
Document 01: Adjust chapter numbering

### ISSUE THREAD

**Issue by anermina** [metanorma/mn-samples-plateau#113]
Procedures: different chapter numbers.
→ ADOC modification may be possible, but will it affect the template Pattern B

![image](https://github.com/user-attachments/assets/f2a55290-001a-492f-bd91-bdb91bed0ccf)

_42nd comment from Plateau team_

**Comment by ronaldtse** [comment]
Superseded and addressed in:
* https://github.com/metanorma/metanorma-plateau/issues/68
