### ISSUE TITLE
Develop proper presentation for ModSpec requirements

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-plateau#119]
Right now they look like this
<img width="779" alt="Screenshot 2024-07-19 at 8 03 17 AM" src="https://github.com/user-attachments/assets/28a8759d-b92f-4861-bdbd-39ac5c9f768d">
<img width="808" alt="Screenshot 2024-07-19 at 8 03 25 AM" src="https://github.com/user-attachments/assets/a7af82e5-5bda-4f19-b8b7-1b6d37ddf2be">

But actually, the first one is a requirements class, so the kanji is wrong.

Let's use the following terminology:
* Requirements class: 要件群
* Requirement: 要件
* Recommendation: 推奨 or 推奨事項 (need to ask)
* Permission: 許可
* Conformance test class: 適合性テスト群
* Conformance test: 適合性テスト

**Comment by opoudjis** [comment]
> Recommendation: 推奨 or 推奨事項 (need to ask)

Will assume the former until you tell me otherwise.

**Comment by opoudjis** [comment]
This is on hold, pending 

> layout requirements of a ModSpec presentation template

Right now, you're going to get what mn-requirements has implemented, which is OGC's rendering. You could do worse.

**Comment by opoudjis** [comment]
This is the current rendering of a Pay Attention requirement:

![Screenshot 2024-08-04 at 00 40 57](https://github.com/user-attachments/assets/44ac06fe-76bb-40f8-bc37-0f0073ace0a1)

**Comment by ReesePlews** [comment]
thank you @opoudjis that looks good, coming along well. 

i am wondering about the indents. i think we discussed that paragraph blocks have one double-byte-space as an indent, but i am concerned indents are possibly being added in more places (the title in the first row of the table actually looks indented on the left compared to the right margin). i will make some checks and open a separate issue if i find anything regarding that.

appreciate all of the work on the plateau flavor!

**Comment by ronaldtse** [comment]
According to @opoudjis the Japanese localization is done. Thanks!
