### ISSUE TITLE
Document 02: Convert "Items of concern" (留意事項) to requirements syntax

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-plateau#121]
In document 02 Annexes, there are many of these "Items of concern" (留意事項):

<img width="591" alt="Screenshot 2024-07-20 at 11 32 58 AM" src="https://github.com/user-attachments/assets/fce6d709-bf1e-4c2d-ac7f-65733ddf16fb">

You can find them using this regex:
<img width="363" alt="Screenshot 2024-07-20 at 11 35 13 AM" src="https://github.com/user-attachments/assets/ca73cc36-037e-4bb2-a348-bc1140628d82">

* Not all Annexes have these "Items of concern"
* For the Annex that have these, let me convert one 

`sources/002-v4/sections/appendix-O/section-03.adoc`:
```adoc
====== 作業手順（立体の場合）

①　航空写真又は航空レーザ点群より、都市設備の上方からの正射影の外周を取得する。

②　航空写真から作成した点群、又は航空レーザ点群から、前項で作成した外周に含まれる点のうち、最高高さを取得し、①で取得した外周に付与する。

③　前項で作成した高さをもった外周を、地表面の高さまで下向きに押し出し、立体を作成する。

なお、地表面が傾斜している場合は、底面の高さを傾斜している最低の地表面の高さとする。これは都市設備が地表面から浮かないようにするためである。

留意事項1：　LOD1における幾何オブジェクトの取得について

道路台帳、道路施設台帳 （植栽）などの各種台帳の付属図面がGISデータとして整備されている場合は、都市設備の位置や形状が含まれるため、LOD1の立体を立ち上げる底面として利用できる。ただし、都市設備の多くは点や線でその形状が作成されており、立体として立ち上げるために必要な面になっていない場合がある。

航空写真や航空レーザ点群を用いて外周の正射影を取得し、これに高さを与えることを標準的な作業手順とするが、電柱やガードレール、交通信号機、道路照明のように、その形状が規格化されているものについては、例えば、電柱の外周を直径30㎝の円形とし、高さは10mとする、というように外周の径や高さ等に一律の値を与えてもよい。

一律値によるデータ作成の可否については3D都市モデルの整備主体と協議し合意を得ること。

また、3D都市モデルの利用者に対しても明示するため、メタデータにその旨を記載すること。

なお、GISデータの利用にあたっては、品質等を含むGISデータの仕様を確認し、利用可否を判断する必要がある。
```

I will extract the content of 留意事項 from immediately after the line to the bottom of the context.

* The first line is the "name"
* The rest is the body
* Need to assign an ID for it, use `/con/{id}` where the ID was given

```
[requirements]
.妥当な災害リスクオブジェクト
====
[%metadata]
identifier:: /con/1
name:: LOD1における幾何オブジェクトの取得について
subject:: 3D都市モデル
statement::
+
--
道路台帳、道路施設台帳 （植栽）などの各種台帳の付属図面がGISデータとして整備されている場合は、都市設備の位置や形状が含まれるため、LOD1の立体を立ち上げる底面として利用できる。ただし、都市設備の多くは点や線でその形状が作成されており、立体として立ち上げるために必要な面になっていない場合がある。

航空写真や航空レーザ点群を用いて外周の正射影を取得し、これに高さを与えることを標準的な作業手順とするが、電柱やガードレール、交通信号機、道路照明のように、その形状が規格化されているものについては、例えば、電柱の外周を直径30㎝の円形とし、高さは10mとする、というように外周の径や高さ等に一律の値を与えてもよい。

一律値によるデータ作成の可否については3D都市モデルの整備主体と協議し合意を得ること。

また、3D都市モデルの利用者に対しても明示するため、メタデータにその旨を記載すること。

なお、GISデータの利用にあたっては、品質等を含むGISデータの仕様を確認し、利用可否を判断する必要がある。
--
====
```

**Comment by anermina** [comment]
It seems some of the "Items of concern" do not have a title in the first line, e.g. 002-v4/sections/section-01:

![image](https://github.com/user-attachments/assets/158cfb8d-2cb9-45e0-b6a6-7b8818af9b43)

I suppose for these we should use GPT for the title generation (still without the "name" attribute?).

Should the note blocks also be a part of the requirement?

**Comment by ronaldtse** [comment]
@anermina yes, please help add a title with GPT.

Let's keep the notes separate for now. Thanks!
