### ISSUE TITLE
PDF: Exception in thread "main" java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn-samples-plateau#147]
Source issue: https://github.com/metanorma/mn-samples-plateau/pull/129

Source document: https://github.com/metanorma/mn-samples-plateau/tree/main/sources/001-v4

The Java heap space is 3Gb (`-Xmx3g`):
`java -Xss10m -Xmx3g -Djava.awt.headless=true -Duser.home=C:/Users/TestUser -jar C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/mn2pdf-1.96/bin/mn2pdf.jar --xml-file "C:/Users/TestUser/AppData/Local/Temp/document20240820-14216-nqjje3.xml" --xsl-file "C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-plateau-0.1.3/lib/isodoc/plateau/plateau.international-standard.xsl" --pdf-file "D:/Work/Metanorma/repositories/mn-samples-plateau/sources/001-v4/document.pdf" --syntax-highlight  --font-manifest "C:/Users/TestUser/AppData/Local/Temp/fontist_locations20240820-14216-xsjmpq.yml"`

Output:
```
[mn2pdf] [INFO] Intermediate format. Rendered page #677.
[mn2pdf] [INFO] Intermediate format. Rendered page #678.
[mn2pdf] [INFO] Processing of Intermediate Format with information about the table's widths (table_if.xsl) ...
[mn2pdf] [INFO] Generated successfully!
[mn2pdf] [INFO] Generation XML with table's widths ...
[mn2pdf] [INFO] Generated successfully!
[mn2pdf] [INFO] XSL-FO file preparation...
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOfRange(Arrays.java:3664)
...
```

**Comment by ronaldtse** [comment]
@Intelligent2013 so this current branch/document is problematic because it is broken. The entire document body is treated as a single source code block. This is likely the cause of the problem.

I'm not sure if it's worth investigating or fixing.

**Comment by Intelligent2013** [comment]
@ronaldtse yes, I sure that the issue occurs due the big sourcecode block. The reason in the file
`mn-samples-plateau\sources\001-v4\sections\section-04\section-07.adoc` - no `----` after the code block `{% render 'gml_dict_template', root: root, filename: filename %}`:


```adoc
====== Waterway_function.xml

lutaml_gml_dictionary::iur/codelists/3.1/Waterway_function.xml[template="gml_dict_template.liquid",context=dict]
----
{% render 'gml_dict_template', root: root, filename: filename %}

====== WaterwayDetailAttribute_routeDirection.xml
```

I've tried to add `----` after the block:
```adoc
----
{% render 'gml_dict_template', root: root, filename: filename %}
----
```

but now the errors occurs about the missing `001-v4/iur/codelists/3.1/Common_districtAndZonesType.xml`:
```
C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-plugin-lutaml-0.7.6/lib/metanorma/plugin/lutaml/lutaml_gml_dictionary_base.rb:31:in `read': No such file or directory @ rb_sysopen - D:/Work/Metanorma/repositories/mn-samples-plateau/sources/001-v4/iur/codelists/3.1/Common_districtAndZonesType.xml (Errno::ENOENT)
```

**Comment by Intelligent2013** [comment]
I've found the updates in https://github.com/metanorma/mn-samples-plateau/pull/146/files already.
Closing.

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 .

**Comment by ReesePlews** [comment]
@Intelligent2013 and @ronaldtse thanks guys for working on this so promptly!
