### ISSUE TITLE
Use Japanese bibliography render style

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-plateau#148]
Notice that the bibliography rendering style uses "period" which is not used in Japanese.

<img width="833" alt="Screenshot 2024-07-15 at 8 40 18 PM" src="https://github.com/user-attachments/assets/81b6c597-a78f-49d2-9635-9ef3ba480d23">

Proper JIS rendering of the bibliography:

<img width="332" alt="image" src="https://github.com/user-attachments/assets/9323cefe-466d-4fcb-8da5-3bf588683a54">

<img width="340" alt="image" src="https://github.com/user-attachments/assets/50ed13d6-82a4-40b3-b797-db8b683ad8a8">

_Originally posted by @ronaldtse in https://github.com/metanorma/mn-samples-plateau/issues/112#issuecomment-2230217706_

**Comment by opoudjis** [comment]
This is not a language-specific thing, since it is being applied to English references; instead, I'm going to make this a JIS relaton-render template, to be inherited by Plateau. We also already have had to deal with Japanese avoiding italics.

**Comment by opoudjis** [comment]
No, we will just remove the final full stop from citation rendering.

**Comment by opoudjis** [comment]
In references in ISO (inherited), need to i18n "[website]"

**Comment by opoudjis** [comment]
![Screenshot 2024-08-21 at 00 51 19](https://github.com/user-attachments/assets/189f0bc3-6519-422d-b965-70b187e02f6d)
