### ISSUE TITLE
PLATEAU team: IUR codelists: some tables mark selective values as "prohibited" （使用不可）

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-plateau#149]
There are 6 instances:

<img width="585" alt="Screenshot 2024-08-21 at 1 55 19 PM" src="https://github.com/user-attachments/assets/eb72fbfa-b0d1-43d8-bf63-2df810def152">

These 6 tables are all about the same GML XML file `DataQualityAttribute_lod1HeightType.xml`, however, in rendering there are certain values marked "prohibited" （使用不可） in the case of those particular classes.

This selection is not possible when rendering the file through `lutaml_gml_dictionary`.

Possible solutions:

* Provide differentiated codelist values using new codelists, e.g. a new codelist that doesn't have 7-9.
* Alternatively, a separate NOTE that describes what values apply or don't apply. 

```adoc
====== DataQualityAttribute_lod1HeightType.xml

TODO: This table cannot be recreated because some values are marked "（使用不可）".

lutaml_gml_dictionary::iur/codelists/3.1/DataQualityAttribute_lod1HeightType.xml[template="gml_dict_template.liquid",context=dict]

// | （使用不可）7 | 建築確認申請書類等に記載された「建築物の高さ」
// | （使用不可）8 | 都市計画基礎調査（建物利用現況）の「高さ（m）」
// | （使用不可）9 | 階高3m×都市計画基礎調査（建物利用現況）の「階数・地上（階）」による推定値
// | 10 | 図面から取得した高さ
// | （使用不可）0 | 取得不可のため一律値（3m）

[.source]
<<gsi_building_data_manual>>
```

```adoc
====== DataQualityAttribute_lod1HeightType.xml

TODO: This table cannot be recreated because some values are marked "（使用不可）".

lutaml_gml_dictionary::iur/codelists/3.1/DataQualityAttribute_lod1HeightType.xml[template="gml_dict_template.liquid",context=dict]

// | （使用不可）7 | 建築確認申請書類等に記載された「建築物の高さ」
// | （使用不可）8 | 都市計画基礎調査（建物利用現況）の「高さ（m）」
// | （使用不可）9 | 階高3m×都市計画基礎調査（建物利用現況）の「階数・地上（階）」による推定値
// | 10 | 図面から取得した高さ
// | 0 | 取得不可のため一律値（3m）

[.source]
<<gsi_building_data_manual>>
```

```adoc
====== DataQualityAttribute_lod1HeightType.xml

TODO: This table cannot be recreated because some values are marked "（使用不可）".

lutaml_gml_dictionary::iur/codelists/3.1/DataQualityAttribute_lod1HeightType.xml[template="gml_dict_template.liquid",context=dict]

// | （使用不可）1 | 点群から取得_最高高さ
// | （使用不可）2 | 点群から取得_中央値
// | （使用不可）3 | 点群から取得_平均値
// | （使用不可）4 | 点群から取得_最頻値
// | （使用不可）5 | 点群から取得_最低値
// | （使用不可）6 | 航空写真図化_最高高さ
// | （使用不可）7 | 建築確認申請書類等に記載された「建築物の高さ」
// | （使用不可）8 | 都市計画基礎調査（建物利用現況）の「高さ（m）」
// | （使用不可）9 | 階高3m×都市計画基礎調査（建物利用現況）の「階数・地上（階）」による推定値
// | 10 | 図面から取得した高さ
// | （使用不可）0 | 取得不可のため一律値（3m）

[.source]
<<gsi_building_data_manual>>
```

**Comment by Chika96** [comment]
”使用不可” is a operational note, so you don't have to autogenetate the note from the codelists.
These are different for each class, and we'll describe which codes are applicable or not in the definition of each class as same as inheritated attributes.

**Comment by ReesePlews** [comment]
thank you @Chika96, does this mean you will be revising the description in the original XML codelist files?

**Comment by ronaldtse** [comment]
I believe @Chika96 will describe "what codes are applicable for each class" inside the Enterprise Architect model, so there is nothing for us to do here.

**Comment by Chika96** [comment]
@ronaldtse  That's right, and we don't have to revise XML codelist files, so "使用不可" is no longer on the tables.

**Comment by ReesePlews** [comment]
this issue can be closed; the `lutaml_gml_dictionary` command is working very well and the tables are being correctly generated based on the xml files from the official web site. in the current document the `TODO` notes are being commented out.

@ronaldtse @Chika96 @AIS-RyoMukai
