### ISSUE TITLE
PLATEAU team: IUR codelists: missing file `CityFurniture_lodType.xml`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-plateau#151]
The file `CityFurniture_lodType.xml` simply doesn't exist in IUR.

Please provide source.

```adoc
====== CityFurniture_lodType.xml

TODO: This file is not present.

// lutaml_gml_dictionary::iur/codelists/3.1/CityFurniture_lodType.xml[template="gml_dict_template.liquid",context=dict]

[cols="3a,22a"]
|===
| ファイル名 | CityFurniture_lodType.xml

h| ファイルURL | https://www.geospatial.jp/iur/codelists/3.1/CityFurniture_lodType.xml
h| コード h| 説明

| 3.0 | 都市設備の主要な部分同士の接続部を表現しない。
| 3.1 | 都市設備の主要な部分同士の接続部を表現する。

|===
```

**Comment by Chika96** [comment]
@ronaldtse 
I will email you the xml code list file. There seems to be a security issue and I am unable to upload the file here.

**Comment by ronaldtse** [comment]
@Chika96 if you can ZIP the file it can be uploaded here.

**Comment by ronaldtse** [comment]
File provided by @Chika96 , which will be officially added to the i-UR archive .

[CityFurniture_lodType.xml.zip](https://github.com/user-attachments/files/16724719/CityFurniture_lodType.xml.zip)
