### ISSUE TITLE
PDF: lists in change history preface missing list labels

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-plateau#160]
In the change history preface, the lists are missing list labels in PDF:

<img width="530" alt="Screenshot 2024-08-23 at 1 11 08 PM" src="https://github.com/user-attachments/assets/18485d3d-8d8d-4a89-b65d-2f3dabc10ae0">

_Originally posted by @ronaldtse in https://github.com/metanorma/mn-samples-plateau/issues/159#issuecomment-2306304867_

**Comment by Intelligent2013** [comment]
The issue relates to whole document, not only the change history.
The attribute `label` is empty in the Presentation XML:
```xml
<ol id="_365868f7-db69-873c-d66b-d2b3d4ec8fbf" type="arabic">
	<li id="_0de114c7-1a1b-4944-86aa-0d67130f81a3" label="">
		<p id="_87fe0584-0308-b868-69a4-b0d335d481a3">都市に関わる様々な地理空間データを格納する基盤（オープンデータ化を含む）</p>
	</li>
	<li id="_c48dad76-e063-4dea-9281-5b3275ab0655" label="">
		<p id="_ff6def13-2aee-b318-ac5b-68789c067f0f">3次元空間における都市計画決定情報の可視化</p>
	</li>
	<li id="_b8f92982-2a32-48ae-97d3-cfed7fd98db5" label="">
		<p id="_9a1c0cf0-9bf5-e87b-67c8-cd3111b70668">災害リスク情報の3次元可視化</p>
	</li>
</ol>
```

@opoudjis could you check what's happened?

**Comment by opoudjis** [comment]
This was fixed in https://github.com/metanorma/metanorma-plateau/commit/ab5f334bab71bd305b98d8bc85d31161e777e6d5 . Please confirm.

**Comment by Intelligent2013** [comment]
Confirmed:
![image](https://github.com/user-attachments/assets/21071a14-3349-44b4-9a3a-7150893f8fb2)

@opoudjis thanks!
