### ISSUE TITLE
(Urgent) All builds failing due to relaton-plateau crash at end of site generate

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-plateau#166]
@andrew2net please help investigate. 

Reported by @ReesePlews

**Comment by andrew2net** [comment]
@ronaldtse how to reproduce the crash?

**Comment by ronaldtse** [comment]
The crash is seen in all builds:
* https://github.com/metanorma/mn-samples-plateau/actions/runs/10562694995

**Comment by andrew2net** [comment]
> The crash is seen in all builds:
> 
> * https://github.com/metanorma/mn-samples-plateau/actions/runs/10562694995

This was fixed in relaton-plateau v1.19.3 https://github.com/relaton/relaton-plateau/issues/14
But the GHA still uses v1.19.2

**Comment by andrew2net** [comment]
BTW I got 2 issues when running the build locally:
- `isodoc` gem wasn't installed previously on my comp and it's not in this repo's dependencies, the build fails until I installed the gem by hand
- Default limit for open files in not enough so I got the error `Jing failed with error: jing execution failed: Too many open files` and had to increase the limit.

**Comment by ReesePlews** [comment]
hello @andrew2net thank you for checking into this problem. is there an update or any other additional information I can provide to you? 

> But the GHA still uses v1.19.2

is the "GHA" the `docker.yml` file?  i did not see any "version" information in that file.  if an update will fix this problem, please consult with @ronaldtse and update it. 

regarding your statement:

> `isodoc `gem wasn't installed previously on my comp and it's not in this repo's dependencies, the build fails until I installed the gem by hand

when i do a `bundle update` this is the isodoc version i get

`Using isodoc 2.11.1 from https://github.com/metanorma/isodoc (at main@1d98089)`

do you think this is correct or is a different version needed?

i also did a manual install of isodoc but the same version 2.11.1 was installed.

during that manual install of isodoc there was the following message at the end:
```
A new release of RubyGems is available: 3.5.9 → 3.5.18!
Run `gem update --system 3.5.18` to update your installation.
```
i dont think it makes a difference but i have updated RubyGems as instructed and it appears to be successfully updated. 

thank you.

**Comment by andrew2net** [comment]
> is the "GHA" the `docker.yml` file? i did not see any "version" information in that file. if an update will fix this problem, please consult with @ronaldtse and update it.

@ReesePlews The GHA is "GitHub Actions", which runs the build. The old version could be cached in GHA, but since a docker container is used it's more likely it's installed inside the container. You can see the version number in the log:
https://github.com/metanorma/mn-samples-plateau/actions/runs/10562694995/job/29261234226#step:6:4457
So we need to ask whoever supports the container to rebuild it with updated relaton-plateau version.

**Comment by ronaldtse** [comment]
This will be fixed once @opoudjis releases the new Metanorma-cli which will trigger the new build if the container.

**Comment by ReesePlews** [comment]
hi @ronaldtse thanks for the update. and that build will merge in all of the recent commits and PRs to the "main" branch?

**Comment by ronaldtse** [comment]
@ReesePlews no, it will just fix the build errors.

**Comment by opoudjis** [comment]
Fixing code and merging PRs to code is my responsibility, and that happens every two weeks.

Fixing documents and merging PRs is an editorial responsibility, and is a separate activity.

**Comment by ronaldtse** [comment]
@CAMOBAP @opoudjis can we please get this issue addressed? Every PR is breaking, the build is breaking, and this is just unacceptable to the client.

**Comment by ronaldtse** [comment]
The client wants to compile the document themselves. It is not currently possible. We need to fix this instead of telling the client "wait for 2 weeks and pray that it works".

**Comment by ronaldtse** [comment]
The client is wondering **why** it takes 2 weeks for the document to be fixed.

**Comment by ronaldtse** [comment]
@CAMOBAP This repository contains a Gemfile using an isodoc git gem, which is not released.

How can we make the Docker container work with this?

Related to: https://github.com/metanorma/mn-samples-plateau/blob/main/Gemfile

**Comment by ronaldtse** [comment]
Creating a new issue instead. This is not happening as described.
