### ISSUE TITLE
spelling: running list of spelling errors to address

### ISSUE THREAD

**Issue by ReesePlews** [metanorma/mn-samples-plateau#173]
### doc01

| misspelling |  correct spelling|
| -- | -- |
| TransportationComlex  |  TransportationComplex  |
|bldg: Building *1 | bldg:Building | 

-----

### doc02

| misspelling |  correct spelling|
| -- | -- |
|AnnexB　妥当な幾何オブジェクト  |  妥当な幾何オブジェクト | 

| xrefs in need of updating |
| -- |
| ##Annex B |

*1 one instance of this found 2024-11-29

**Comment by ReesePlews** [comment]
hello @AIS-RyoMukai if you can easily add these revisions to an open PR it would be helpful. if not, tell me and i will correct them in a couple of days. thank you

**Comment by AIS-RyoMukai** [comment]
@ReesePlews  @AAS-YknKawakita 
最新メインで未対応なら、次回マージ分で修正します
If it is not supported in the latest main version, we will fix it in the next merge.

**Comment by ReesePlews** [comment]
hello @AIS-RyoMukai no they have not been addressed yet, i will check them, dont worry about this. let me know when your updates are finished. thank you
