### ISSUE TITLE
alignment of normative references entries between doc1 and doc2

### ISSUE THREAD

**Issue by ReesePlews** [metanorma/mn-samples-plateau#178]
when unifying code list tables between doc1 and doc2, some of those in doc01 have specific source references. however some of those source references may not exist in doc2. 

this normative ref is used in doc1:

`IFC2x3 CV2.0, buildingSMART International. IFC 2×3 Coordination View 2.0. ⼊⼿先: https://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/FINAL/HTML/
`

it does not exist in doc2 but is needed for this table (which came from doc01)

![image](https://github.com/user-attachments/assets/42bc01d4-2a40-4b41-89d4-cc6901faafb4)

Question: should those needed source references be added to doc2 just so the source to be resolved for a codelist table?

@AIS-RyoMukai @Chika96 please advise.

**Comment by AIS-RyoMukai** [comment]
We may have talked with Kurokawa before, but you can tune in to 001.

**Comment by ReesePlews** [comment]
thank you @AIS-RyoMukai i will add reference

`IFC2x3 CV2.0, buildingSMART International. IFC 2×3 Coordination View 2.0. ⼊⼿先: https://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/FINAL/HTML/ `

to doc2. thank you

**Comment by ReesePlews** [comment]
we will track this in #179
