### ISSUE TITLE
Missing navigation item

### ISSUE THREAD

**Issue by strogonoff** [metanorma/mn-samples-plateau#180]
This is probably a stupid question. In https://www.mlit.go.jp/plateaudocument/ I am seeing a navigation item 改定の概要, but it seems to appear nowhere in XML I downloaded from the action build result ZIP, am I missing something? Did they change their document or do we call it differently?

I did find はじめに in a few places (still wrapping my head around XML).

cc @opoudjis

**Comment by strogonoff** [comment]
I that see we call it 改訂履歴.

**Comment by opoudjis** [comment]
````
[.preface,type=publication-history]
== 改定の概要
````

in mn-samples-plateau/sources/002-v4/sections/00-history.adoc

**Comment by ronaldtse** [comment]
@strogonoff the online version is no longer current. A lot of changes have occurred.

For this particular "revision history", it has been standardized:
* https://github.com/metanorma/mn-samples-plateau/issues/158
