### ISSUE TITLE
`displayorder` reversed between  目次 and はじめに

### ISSUE THREAD

**Issue by strogonoff** [metanorma/mn-samples-plateau#181]
Another stupid question. I see that 目次 goes at `displayorder=2`, and はじめに goes at `displayorder=1`, but in HTML they appear in reverse (naturally). Why such `displayorder` and what logic swaps them?

cc @opoudjis

**Comment by strogonoff** [comment]
Perhaps I should clarify that I am looking at the navigation sidebar (but in the main document contents area there’s no 目次 anyway).

**Comment by strogonoff** [comment]
cc @ronaldtse if you know…

**Comment by strogonoff** [comment]
Actually, I don’t see a `<clause>` corresponding to はじめに/abstract (I suppose it’s the `<abstract>` itself then).

**Comment by strogonoff** [comment]
I suppose the logic goes as this:

- `clause type=toc` is the header for ToC, so it goes up (despite `displayorder`)
- the rest of the clauses are sorted according to `displayorder`
- if there is no `displayorder` (like for nested clauses), sort in order of appearance

**Comment by strogonoff** [comment]
That logic gets me somewhere like this, which I suppose is acceptable:

<img width="354" alt="Screenshot 2024-09-24 at 07 30 03" src="https://github.com/user-attachments/assets/755a22a2-8ab8-400a-9931-2e096258802c">

**Comment by ReesePlews** [comment]
hello @strogonoff, in the current genearate document PDF the order for the front matter sections is:

cover page
はじめに
改訂履歴
目次

i have only been checking the PDF.

**Comment by strogonoff** [comment]
Thanks @ReesePlews but this was more of a question about ordering mismatch between XML and HTML to Nick.

**Comment by opoudjis** [comment]
@strogonoff If you want me to pay attention, you need to (a) assign me the ticket, and (b) assign the ticket to the Metanorma project. If you do not do these things, it may be up to a week until I notice it.

**Comment by opoudjis** [comment]
This is likely an old oversight. The contents of the HTML were being rendered in the order they were found in the XML, but enough edge cases happened, that the PDF, and then the HTML, use displayorder for ordering rendering instead.

... The code generating ToC for HTML is ignoring displayorder. The current ToC ordering is a bug, and I will fix it.

**Comment by strogonoff** [comment]
@opoudjis Understood, I will keep this in mind for urgent questions. In this case I would just ask you on a call some time if I do not figure it out myself, plus it captures my thoughts and could potentially get an answer from Ronald. Different styles of ticket processing, maybe.

**Comment by strogonoff** [comment]
> This is an old oversight. The contents of the HTML were being rendered in the order they were found in the XML, but enough edge cases happened, that the PDF, and then the HTML, use displayorder for ordering rendering instead.
> 
> ... The code generating ToC for HTML is ignoring displayorder: I simply forgot to update it. The current ToC ordering is a bug, and I will fix it.

Great. I am ignoring it too in the first iteration (and will keep going so, then).

**Comment by opoudjis** [comment]
Yes, I'm asking for proactive highlighting of issues because (a) we don't have a ticket/project manager at all, (b) I work limited hours, and (c) you can fill in at your own discretion :)

I'm coming out of one big chunk of work into another. Please gather up questions as you go: some of them like this may be bugs, some of them I'll need to talk you through.

**Comment by strogonoff** [comment]
> This is an old oversight. The contents of the HTML were being rendered in the order they were found in the XML, but enough edge cases happened, that the PDF, and then the HTML, use displayorder for ordering rendering instead.
> 
> ... The code generating ToC for HTML is ignoring displayorder: I simply forgot to update it. The current ToC ordering is a bug, and I will fix it.

Wait, scrap my previous comment. More questions.

1. There is an extra question and that is ToC header is an entry in navigation but technically has no contents in document area
2. What are the edge cases. We can discuss later I suppose

**Comment by opoudjis** [comment]
> The ToC header itself is an entry in navigation but technically has no contents in document area, hmm.

The ToC header is  a placeholder in the Presentation XML, which different output formats can and do populate differently: what a ToC looks like in Word, HTML, and PDF is so different, I did not feel there was any point putting content in at the Presentation XML level. Each of them derive the ToC separately, from the generated local content (Word, HTML, PDF document), and not from a common source XML.

So the HTML renderer has code that iterates through the headings generated in the HTML. That actually makes it all the more puzzling that displayorder is not being respected, will need to investigate.

**Comment by strogonoff** [comment]
Got it.

What are your thoughts on this: 

1. To me it seemed like ToC item itself was the header for navigation, I was mistaken on that? 
2. If ToC item with displayorder is intended to be part of navigation, can I still get navigation header from somewhere? 
3. If I show it as an item abe according to displayorder, I will have “abstract” item then ToC item, which makes sense to me. This is not a question, I guess.

**Comment by strogonoff** [comment]
> That actually makes it all the more puzzling that displayorder is not being respected, will need to investigate.

May have to do with the fact that it is a sidebar. Perhaps someone had the same idea as me, and wanted a label for the sidebar, and repurposed the ToC item for that by swapping order only in the sidebar.

**Comment by opoudjis** [comment]
I do not understand your questions. Try illustrated examples?

**Comment by strogonoff** [comment]
Sure. I mean the equivalent of this Contents header on this screenshot. 

![IMG_4525](https://github.com/user-attachments/assets/4372112e-cf75-4706-a2ea-0487d996f40e)


 It is not a ToC item itself, but perhaps it is assumed that it is always called the same as the ToC item, and that is why ToC entry in MN HTML was moved up, despite displayorder, to act as this  header.

**Comment by strogonoff** [comment]
If my above comment is correct, then I would ask if there is a more appropriate way to get that Contents label without that sort of machination.

**Comment by strogonoff** [comment]
(Plateau has equivalent layout for the purposes of this question, just simpler styling.)

**Comment by ronaldtse** [comment]
As a side note, there is a difference in location of the TOC as a part of the document. Sometimes there are pre-TOC sections, sometimes the TOC is the first element. (Sometimes an Abstract goes before TOC, sometimes after)

In an ebook reader, I believe that these “meta-document sections” (TOC, Index) should remain as “meta”, ie. They are no longer part of the document flow.

**Comment by opoudjis** [comment]
> It is not a ToC item itself, but perhaps it is assumed that it is always called the same as the ToC item for ToC itself, and that is why ToC entry in MN HTML was moved up, despite displayorder, to act as such header.

OK, I think I understand what is going on, and you really aren't helping with how you posed the question.

In the Presentation XML, you get:

````
<preface><abstract id="_abstract" displayorder="1"><title>Abstract</title><p id="_f36daa4a-805d-5372-2104-607845a55e5b">I am an abstract</p>
</abstract>
<clause type="toc" id="_0da38adc-2331-404b-b366-8f9ca202d398" displayorder="2"><title depth="1">Contents</title></clause>
 </preface>
````

Now, it is indeed true that the Table of Contents is the second thing to render, after abstracts. And that is being observed in PDF and DOC output.

But in HTML, we have decided to ALWAYS render the table of contents as a sidebar. That means:

* The ToC itself is not included in the generated table of contents. It is in fact explicitly skipped. What would the point of including it be? It isn't in the main window at all, that goes straight from Abstract to the main body.
* The "Contents" is indeed just a heading, and not a Table of Contents item.

So:

> To me it seemed like ToC item itself was the header for navigation, I was mistaken on that? 

The "Contents" header is just a header. It is not an item within the table of contents. I have no idea what you mean by "header for navigation".

> I needed to get a label for the topmost (unclickable?) title of the sidebar.

It is a header. As I render the HTML, it has an ID because all IDs do. If you want to get its ID, it is `/div[@id = 'toc']/h1`. In fact, if you look at the current HTML, it doesn't even have a separate ID for the header within `/div[@id = 'toc']` 👍 ````

````
<div id="toc"><h1 class="IntroTitle">
<a class="anchor" href="#_0da38adc-2331-404b-b366-8f9ca202d398"></a>
<a class="header" href="#_0da38adc-2331-404b-b366-8f9ca202d398">Contents</a></h1>
<ul>
....
````

> If ToC item with displayorder is intended to be part of navigation, can I still get navigation header from somewhere?

You are doing this from scratch, you get to decide. I have excluded it from navigation, precisely because it is not part of the document flow (to use Ronald's terminology). If you include it, as I have done for PDF and DOC, you decide where to include it; the ToC itself will be the body of the clause of which the "Contents" is the header.

> If I show it as an item and according to displayorder, I will have “abstract” item then ToC item, which makes sense to me. This is not a question, I guess.

Yes, and that is the current behaviour in PDF and DOC.

There is no reversal of displayorder, since the ToC itself is not part of the ToC clause in HTML; so this is an invalid ticket.
