### ISSUE TITLE
Obtaining semantic XML from GHA: `document.xml` is missing for 001

### ISSUE THREAD

**Issue by strogonoff** [metanorma/mn-samples-plateau#188]
cc @ronaldtse 

Any chance downloadable GHA artefacts could include Semantic XML as well?

**Comment by ronaldtse** [comment]
The GHA artifacts already contain both.

**Comment by strogonoff** [comment]
No, there is only one XML per document.

**Comment by strogonoff** [comment]
Correction, there is a file called `document.xml` but it’s only present for `002-v4`. Can we include it for `001-v4`, as well?

**Comment by opoudjis** [comment]
@strogonoff As I have already told you, both verbally and in the documentation, the Presentation XML file contains the Semantic XML with appropriate prefixing, and that is the file you MUST consume.

The output formats for each file are a document attribute, `:mn-output-extensions:`. You will see in sources/001-v4/document.adoc

````
:mn-output-extensions:html,pdf
````

and in sources/002-v4/document.adoc

````
:mn-output-extensions: xml,html,pdf,rxl
````

If you want to output document.xml as well into the compilation, you now know what to do.

We will have EXTREMELY limited patience about RTFM.
