### ISSUE TITLE
Fix issues in 001-v4

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-plateau#207]
Discovered by @strogonoff :

## Presence of `===` in text

Generated:
![WhatsApp Image 2024-10-20 at 19 28 37](https://github.com/user-attachments/assets/008deb44-0a8b-4e41-b2a3-4ae83afba6f3)

Original: 
<img width="666" alt="Screenshot 2024-10-20 at 11 58 28 PM" src="https://github.com/user-attachments/assets/64740730-8723-4b51-a91f-e2d7f0955055">
<img width="670" alt="Screenshot 2024-10-20 at 11 58 35 PM" src="https://github.com/user-attachments/assets/fa01c2f7-a4ff-45e1-8993-28522dd71959">

## Missing line breaks

![WhatsApp Image 2024-10-20 at 11 24 55](https://github.com/user-attachments/assets/9e84ef4b-67db-424c-acd6-d72c35d2e351)

Original:
<img width="654" alt="Screenshot 2024-10-20 at 11 59 45 PM" src="https://github.com/user-attachments/assets/f1bc919c-0cc1-4785-a903-6ea7920cdd1d">

## Missing line breaks 2

![WhatsApp Image 2024-10-20 at 02 48 05](https://github.com/user-attachments/assets/f527c334-cdfc-4fb1-989e-be86a70e6fea)

<img width="647" alt="Screenshot 2024-10-21 at 12 00 43 AM" src="https://github.com/user-attachments/assets/e4dfa469-d18e-41fd-a094-8efd56274eb4">

**Comment by ReesePlews** [comment]
@strogonoff and @ronaldtse thanks for identifying and fixing those issues! appreciate the continued checking of the document!
