### ISSUE TITLE
(URGENT: HTML/PDF) Broken normative references shown with a repeating reference tag (number) in 001-v5

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-plateau#255]
HTML:
<img width="1278" alt="Screenshot 2024-12-10 at 12 29 03 PM" src="https://github.com/user-attachments/assets/d0783567-3811-4bb2-9ba8-442715fa0cc5">

PDF:
<img width="833" alt="Screenshot 2024-12-10 at 12 29 18 PM" src="https://github.com/user-attachments/assets/6e3c1a54-8499-4ed2-aeab-4f8b011caaf5">

**Comment by opoudjis** [comment]
This goes all the way up to ISO if not isodoc itself, as an unforeseen usage of Normative References.

In bibliographies, you can supply numbers as document identifiers: they will be renumbered consecutively from 1.

This was not foreseen in normative references, which in ISO are meant to be standards. So any numbers in normative references are not being renumbered.

I have the added problem that any such numbering will need to encompass both normative references and bibliographies.

**Comment by opoudjis** [comment]
I am running out of time to do these. You can in the interim number these with the intended numbers.

**Comment by opoudjis** [comment]
So long as there isn't crazy arbitrary reordering of references between Semantic and Presentation XML, this should be a one-line fix. Let's find out..

**Comment by opoudjis** [comment]
No, not that straightforward.

In normative references, if no numeric reference is supplied, we cannot insert one, as we do in bibliographies.

**Comment by opoudjis** [comment]
This change  is getting rid of the distinction between metanorma and metanorma-ordinal as docidentifier types in normative references: [110] is not going to displace ISO 712 in the example references. That's just as well, it was an artificial distinction.

**Comment by opoudjis** [comment]
We have consecutive numbering of normative references:

![Screenshot 2024-12-17 at 18 15 08](https://github.com/user-attachments/assets/2f9b0f13-c6a4-47cc-9a42-253039f02e50)



Numbering resumes in the bibliography. It then skips numbers, and I do not know why, but I ask that you investigate before raising a new ticket. This ticket is done, as it concerns integrating normative references into the consecutive numbering of numbered references.

![Screenshot 2024-12-17 at 18 15 29](https://github.com/user-attachments/assets/f482e210-60cc-4e12-9a02-adb12afc97d1)
