### ISSUE TITLE
(URGENT: PDF) Missing Index page number in TOC and bad rendering of Index

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-plateau#257]
<img width="871" alt="Screenshot 2024-12-10 at 12 33 28 PM" src="https://github.com/user-attachments/assets/281ca093-d5d8-4fa1-9056-c08f70f7a695">

And clicking on the TOC entry of the Index brings me back to the top:
<img width="876" alt="Screenshot 2024-12-10 at 12 33 43 PM" src="https://github.com/user-attachments/assets/e8797bee-b4db-413c-bdc2-a798a4280ae5">

The index is actually placed at the end but the rendering is also strange.

<img width="657" alt="Screenshot 2024-12-10 at 12 34 22 PM" src="https://github.com/user-attachments/assets/29975af2-3f54-4134-a1a7-8f71e1fc1cba">

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://github.com/user-attachments/assets/849cd566-1d31-44e0-981c-798398ed881a)

![image](https://github.com/user-attachments/assets/33a4e511-f763-4035-89ef-2533c48dd2b9)

**Comment by ReesePlews** [comment]
thank you for the quick work @Intelligent2013! we will check this.

**Comment by ronaldtse** [comment]
Thank you @Intelligent2013 !

**Comment by ReesePlews** [comment]
hello @Intelligent2013 are these in the main branch or do we need to wait until the next release to confirm these revisions?

**Comment by Intelligent2013** [comment]
> hello @Intelligent2013 are these in the main branch or do we need to wait until the next release to confirm these revisions?

@ReesePlews the update made in `metanorma-plateau` gem. You need to wait until the next release if you use the docker based solution to generate the PDF. Or you can add the line
```
gem "metanorma-plateau", git: "https://github.com/metanorma/metanorma-plateau", branch: "main"
```
into `Gemfile` and then run:
```
bundle update
bundle exec metanorma sources/002-v4/document.adoc
```

**Comment by ReesePlews** [comment]
hello @Intelligent2013 thank you for the information. we have been using metanorma locally to verify the updates to the branches before we issue the PR and request the merge to main on github. (sorry if my terminology is incorrect here).

my current Gemfile looks like this:

```
source "https://rubygems.org"

gem "metanorma-cli"

# WARNING: only for developers
# gem "metanorma-plateau", git: "https://github.com/metanorma/metanorma-plateau"
# gem "metanorma-iso", git: "https://github.com/metanorma/metanorma-iso"
# gem "isodoc", git: "https://github.com/metanorma/isodoc"
# gem "sassc"
# gem "debug"
# gem "metanorma-plateau", path: "~/src/mn/metanorma-plateau"

# gem "metanorma-plugin-lutaml", git: "https://github.com/metanorma/metanorma-plugin-lutaml"
# gem "metanorma-standoc", git: "https://github.com/metanorma/metanorma-standoc"
# gem "lutaml", git: "https://github.com/lutaml/lutaml"

# for local development
# gem "metanorma-plugin-lutaml", path: "~/src/metanorma/metanorma-plugin-lutaml"
# gem "metanorma-standoc", path: "~/src/metanorma/metanorma-standoc"
# gem "lutaml", path: "~/src/lutaml/lutaml"

```

i will modify it as you have described and see if my results are different. i will report back. thank you.

**Comment by Intelligent2013** [comment]
> my current Gemfile looks like this:

@ReesePlews you can just uncomment the line (remove `# ` at start) :
```
gem "metanorma-plateau", git: "https://github.com/metanorma/metanorma-plateau"
```
