### ISSUE TITLE
possible modspec table number/cross reference issue

### ISSUE THREAD

**Issue by ReesePlews** [metanorma/mn-samples-plateau#265]
originally reported [here](https://github.com/ReesePlews/ribose_discussions/issues/30).

in the plateau project doc 2 (sources/002-v5) [\mn-samples-plateau\sources\002-v5\sections\section-04\section-02.adoc] the client identifies this issue, and believes it to be a possible  modspec numbering issue:

![image](https://github.com/user-attachments/assets/2e5f849f-684c-495d-83f8-cbe9cd5ee063)

in table 5-12: 留意事項31: 不明値の指定方法  there is a link to table 5-3 but it does not seem to jump to 5-3, instead jumps 5-13 or nowhere, difficult to tell exactly.

since this was autogenerated it could be an issue with modspec. could you please check this. thank you.

**Comment by ReesePlews** [comment]
in checking this issue more, it is not random or a single issue.   here is another example.
the cross-reference to table 5-2 (表5－2) does not jump back to table 5-2 but instead seems to just stay on the current page.
![image](https://github.com/user-attachments/assets/88e65e5d-4ae3-4fe3-8de0-b402cd27e23d)

the same happens again here, 
the cross-reference to table 5-4 (表5－4) does not jump back to table 5-4 but instead seems to just stay on the current page.

![image](https://github.com/user-attachments/assets/24f6bccd-404a-48d3-999b-2db010b29d3f)


this is the current document code; 
![image](https://github.com/user-attachments/assets/ea194adb-d20f-4f56-9891-c5739835f7a9)

in table 5-4 on the left i cannot see the cross-reference link; however it is present in table 17 (right upper) and that link points to table 18 (right lower)

it is our understanding these tables were auto-generated, however if that is not the case, are these just simple document issues, and if so, should we can just clean these issues up manually?  please let us know. thank you.

**Comment by opoudjis** [comment]
I am being screwed over by System updates ruining my installation of Ruby (on New Year's Goddamn Eve, no less), and it is currently impossible for me to compile this.

Am trying to address, but I am even more enraged by being let down by my environment than usual.

**Comment by opoudjis** [comment]
> in table 5-12: 留意事項31: 不明値の指定方法 there is a link to table 5-3 but it does not seem to jump to 5-3, instead jumps 5-13 or nowhere, difficult to tell exactly.

The link is

````
<xref target="tab-4-3"><span class="fmt-element-name">表</span><semx element="autonum" source="toc4">5</semx><span class="fmt-autonum-delim">-</span><semx element="autonum" source="tab-4-3">3</semx></xref>
````

But tab-4-3 is indeed Table 5.13:

````
<table id="tab-4-3" autonum="5-13">
````

Now, of the tables, 5-12 is a Modspec table, and "5-13" is a non-Modspec table. What has clearly happened is that Modspec tables have been injected into the document after the initial run of tables were generated, but the cross-references of tables, from what was 5-3 to what is now 5-13, was not updated.

The expected behaviour is that non-Modspec and Modspec tables are both tables, and should be cross-referenced as such.

**Comment by opoudjis** [comment]
This is behaviour inherited from ISO, and will impact ISO as well.

Reproduced in ISO for a two-table document.

**Comment by opoudjis** [comment]
Yes, I see the issue. Requirements are being rendered, including their xrefs, before the table numbering is finalised, so the xrefs are populated with the text of the numbering of non-modspec tables, before modspec tables are added in.

That makes no sense: the xrefs of non-modspec tables (and for that matter of modspec tables) should be deferred until after the tables are generated.

And I've found why:

````
      # any xrefs not yet expanded out to rendering need to be expanded out,
      # so that the identifier instances they contain can be truncated
      def expand_xrefs_in_reqt(table)
        table.xpath(ns(".//xref[not(@style)][string-length() = 0]"))
          .each do |x|
          ref = @xrefs.anchor(x["target"], :xref, false) or next
          x << ref
        end
      end

      def truncate_id_base_in_reqt(table)
        base = @reqt_id_base[table["id"]]
        expand_xrefs_in_reqt(table)
        truncate_id_base_in_reqt1(table, base)
      end
````

Yes, but that should ONLY be applied to cross-references to other modspec tables (which are based on identifiers, and which need to be able to be truncated). Cross-references to normal tables should be left alone.

**Comment by opoudjis** [comment]
Link has been fixed in 5-12, from 5-3 to the correct 5-13:

![Screenshot 2025-01-01 at 00 25 31](https://github.com/user-attachments/assets/ca50887b-9763-4c74-927c-0cc3b0a70ce3)

Link in 5-4 fixed, from 5-2 to the correct 5-5:

![Screenshot 2025-01-01 at 00 27 29](https://github.com/user-attachments/assets/12fea437-9a2c-4eac-ab07-77482c102eec)

Link in 5-17 fixed, from 5-4 to the correct 5-18:

![Screenshot 2025-01-01 at 00 28 35](https://github.com/user-attachments/assets/3ef8b097-84a1-43e7-bad1-624685e3889a)

So the links were all correct, the labels were out of sync and are now fixed. I am releasing the mn-requirements fix immediately.

**Comment by ReesePlews** [comment]
hi @opoudjis thank you for working on the holiday to identify and fix this issue. i will verify with a local compile in the next couples of days and get back to you here with a report.

**Comment by ReesePlews** [comment]
hello @opoudjis i compiled this locally after doing a "bundle update" but it did not give the same results as what you have shown above. do i need to make a special update to my Gemfile to check this? if it will be added to the Jan 6th/7th MN release i will just want to check it then.  thank you.

**Comment by opoudjis** [comment]
I really should have. Confirm that you have updated mn-requirements to 0.4.3. I'll check again before release, but that should be the only gem impacted.
