### ISSUE TITLE
Encode "補足" (Note/Supplement?)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-plateau#37]
<img width="622" alt="Screenshot 2024-06-25 at 12 25 04 PM" src="https://github.com/metanorma/mn-samples-plateau/assets/11865/0685ed6c-2e61-4420-8d75-9f3c80e64dd1">
<img width="575" alt="Screenshot 2024-06-25 at 12 25 19 PM" src="https://github.com/metanorma/mn-samples-plateau/assets/11865/261281ea-bee1-4b1f-91fe-6d9c2480f34b">

```adoc
[cols="1,6"]
|===
| No | L04

h| 品質要素 h| 論理一貫性・定義域一貫性
h| 品質適用範囲 | gml:CodeTypeを型としてもつ地物属性のうち、コードリストを参照している地物属性。
h| 品質評価尺度 | 指定されたコードリストに定義されていない値となっている箇所数。
h| 適合品質水準 | エラーの数が0個の場合に合格。エラーの数が1以上の場合は不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

. gml:CodeTypeに含まれるコードリストへの相対パスを取得する。
. 相対パスで指定されたコードリストに定義された全てのコード値（gml:nameにより記述）を取得する。
. 検査プログラムにより、地物属性の値と取得した全てのコード値との比較を行い、地物属性の値が、コード値と合致しない箇所を数える。 

補足：コードリストへの相対パスは、gml:CodeTypeの属性であるcodeSpaceの値として記述されている。

|===
```

**Comment by ronaldtse** [comment]
These are not yet handled.

**Comment by opoudjis** [comment]
What are these, do you know? Special kinds of note?

**Comment by ronaldtse** [comment]
Technically these are “supplements”, ie. Additional information. 

Let’s ask the PLATEAU team. 

@ReesePlews @Chika96 could this content be encoded as NOTEs (注)？

**Comment by ReesePlews** [comment]
would these be treated as ISO/DIR2 29.6 "NOTES" inside the table boundary or how JIS is handling 注記?

**Comment by ronaldtse** [comment]
Yes. JIS handles 注記 for tables in the same way as ISO, which is at the table footer.

**Comment by Chika96** [comment]
These "補足" information can be treated in the same way as ISO and JIS.

**Comment by ReesePlews** [comment]
hello @ronaldtse and @opoudjis, the client has replied above and we can handle them the same way as ISO and JIS. reply if you need more information, thanks.

**Comment by opoudjis** [comment]
I do need more information.

Are these notes, or something else? If they are just notes, why are they labelled 補足 and not 注記? If 注記  is already implemented in ISO, what in ISO in English does it correspond to? For that matter, what in JIS does 補足  correspond to? Can a table have both 補足 and 注記? If it can, are they numbered separately? Or are we just going to ignore the 補足/注記 distinction, and call instances of notes in tables 補足?

**Comment by ronaldtse** [comment]
@opoudjis we will just handle them as normal NOTEs. There is no need for a separate type of content. Thanks.

**Comment by opoudjis** [comment]
... in which case there is nothing for me to do:

````
[cols="1,6"]
|===
| No | L04

h| 品質要素 h| 論理一貫性・定義域一貫性
h| 品質適用範囲 | gml:CodeTypeを型としてもつ地物属性のうち、コードリストを参照している地物属性。
h| 品質評価尺度 | 指定されたコードリストに定義されていない値となっている箇所数。
h| 適合品質水準 | エラーの数が0個の場合に合格。エラーの数が1以上の場合は不合格。
h| 品質評価手法 | 全数・自動検査を実施する。

. gml:CodeTypeに含まれるコードリストへの相対パスを取得する。
. 相対パスで指定されたコードリストに定義された全てのコード値（gml:nameにより記述）を取得する。
. 検査プログラムにより、地物属性の値と取得した全てのコード値との比較を行い、地物属性の値が、コード値と合致しない箇所を数える。 

|===

NOTE: コードリストへの相対パスは、gml:CodeTypeの属性であるcodeSpaceの値として記述されている。
````

already renders as:

![Screenshot 2024-08-22 at 15 24 02](https://github.com/user-attachments/assets/38e22e00-1581-4123-a882-95bf2a65600e)

following JIS. The label is 注記 not 補足, but you've indicated that's acceptable. 

So, close ticket?

**Comment by ronaldtse** [comment]
Done in #157.
