### ISSUE TITLE
Document 01 & 02: Change numbering in items list

### ISSUE THREAD

**Issue by anermina** [metanorma/mn-samples-plateau#68]
Document 01:
Specification: different specifications for sequential numbers.​

　→ ADOC modification may be possible, but will it affect the template Pattern B​

![image](https://github.com/user-attachments/assets/8edb335f-5060-49a7-9dde-92dba22718c5)

Specification: different specification for sequential numbering Same thereafter.​

　→ ADOC modification may be possible, but will it affect the template Pattern B​

![image](https://github.com/user-attachments/assets/c58028ff-051d-44c6-abe8-87f07ad8f0e4)

Document 02:
Procedure: different specifications for sequential numbers.​
　　→ ADOC modification may be possible, but will it affect the template Pattern B​

![image](https://github.com/metanorma/mn-samples-plateau/assets/55683568/fad0be14-e0e0-46b3-9928-20528f53dbbc)

Procedure: different sequential numbering specifications Same as below.​

　→ ADOC modification may be possible, but will it affect the template Pattern B​

![image](https://github.com/metanorma/mn-samples-plateau/assets/55683568/d6d6acfd-ccb1-4dae-8827-fc90f0d22cf4)

_27th, 31st, 44th and 50th comment from Plateau team_

Related issue: https://github.com/metanorma/mn-samples-plateau/issues/84

**Comment by ronaldtse** [comment]
Done in:
* https://github.com/metanorma/metanorma-plateau/issues/64
* https://github.com/metanorma/metanorma-plateau/issues/68
