### ISSUE TITLE
Document 02: Content differs in the generated document

### ISSUE THREAD

**Issue by anermina** [metanorma/mn-samples-plateau#69]
Procedure: different content?　→ Believed to be ADOC Pattern C.​

![image](https://github.com/metanorma/mn-samples-plateau/assets/55683568/81580557-cebf-4009-866d-4312a12bf8b1)

_45th comment from Plateau team_

**Comment by ronaldtse** [comment]
Done in:
* https://github.com/metanorma/metanorma-plateau/issues/64
* https://github.com/metanorma/metanorma-plateau/issues/83
