### ISSUE TITLE
Document 02: Do not treat commentary as a note

### ISSUE THREAD

**Issue by anermina** [metanorma/mn-samples-plateau#70]
Procedure: commentary is treated as a note. It should be separated from the original note as it is confused with the original note.​

　→ Can the template be used for this purpose? Pattern B​

![image](https://github.com/metanorma/mn-samples-plateau/assets/55683568/2ac647b4-86ee-4a33-92db-eb2487b93a8d)

![image](https://github.com/metanorma/mn-samples-plateau/assets/55683568/3421bdcf-5cf2-4dd3-882e-b52dafa18aa3)

_46th and 47th comment from Plateau team_

**Comment by ronaldtse** [comment]
Done in:
* https://github.com/metanorma/metanorma-plateau/issues/81
