### ISSUE TITLE
Document 01 & 02: Remove numbering for the tables and images without a caption

### ISSUE THREAD

**Issue by anermina** [metanorma/mn-samples-plateau#71]
Specification: all tables are given sequential numbers and the title section is framed.​

　→ It may be possible to delete unnecessary parts in the ADOC, but will this affect the template Pattern B​

Procedures: tables and images without captions are also sequentially numbered, resulting in subsequent misalignment.​

　　→ ADOC modification may be possible, but will it affect the template Pattern B​

Document 01:
![image](https://github.com/user-attachments/assets/4fde6e76-cf4b-47e2-a453-d154ef54333b)

![image](https://github.com/user-attachments/assets/6effee65-3355-4ba2-be01-6a1ebb9cdbff)

![image](https://github.com/user-attachments/assets/04da4dcd-3875-498c-8604-d5503d1eab6b)

Document 02:
![image](https://github.com/metanorma/mn-samples-plateau/assets/55683568/51fa8592-2867-49ac-84f0-9276bc8d02d7)

_3rd, 4th, 10th and 48th comment from Plateau team_

**Comment by ronaldtse** [comment]
Done.
