### ISSUE TITLE
Document 01 & 02: Add underline where needed

### ISSUE THREAD

**Issue by anermina** [metanorma/mn-samples-plateau#72]
Procedure: no underlines Same as above → thought to be an ADOC amendment Pattern C​

Document 01:
![image](https://github.com/user-attachments/assets/2206d690-7897-4a02-9c17-ed61523c6207)

Document 02:
![image](https://github.com/metanorma/mn-samples-plateau/assets/55683568/66ff26f8-d009-498f-a4d1-77cc0013317e)

_5th and 49th comment from Plateau team_

**Comment by anermina** [comment]
> Type 1: really textual content missing underlines (random underlines in text). => please fix in markup.

I think this part is still not fixed. @ronaldtse , could you please confirm that this still needs to be done? Thank you.

**Comment by manuelfuenmayor** [comment]
I'm taking care of that
