### ISSUE TITLE
Document 02: Add line breaks in the examples and reconsider color-coding

### ISSUE THREAD

**Issue by anermina** [metanorma/mn-samples-plateau#74]
Procedure: no line breaks in the section Example 1. Example 2. Do they need to be colour-coded?​

　→ ADOC considered correctable Pattern C.​

![image](https://github.com/metanorma/mn-samples-plateau/assets/55683568/ecac84f0-a629-4492-82d1-da1d3266804d)

_53rd comment from Plateau team_

**Comment by ronaldtse** [comment]
We have not encoded the examples properly yet, but there is nothing to do here since the PLATEAU team has agreed to the following proposals:

* https://github.com/metanorma/metanorma-plateau/issues/71
* https://github.com/metanorma/metanorma-plateau/issues/72
