### ISSUE TITLE
Document 02: Fix markup in table 5-1

### ISSUE THREAD

**Issue by anermina** [metanorma/mn-samples-plateau#75]
Procedure: underbars are missing and italicised in places, line breaks failed in places.​

　→ Believed to be an ADOC modification Pattern C​

![image](https://github.com/metanorma/mn-samples-plateau/assets/55683568/d1435200-1424-41aa-8294-1a425310e09c)

_54th comment from Plateau team_

**Comment by anermina** [comment]
Confirming the fix.

![image](https://github.com/user-attachments/assets/314842cb-da74-4259-9f70-f0fc20ad72fe)

**Comment by ronaldtse** [comment]
Fixed as per @anermina .
