### ISSUE TITLE
Document 01 & 02: Text between square brackets is not generated

### ISSUE THREAD

**Issue by anermina** [metanorma/mn-samples-plateau#77]
Procedure: component missing → likely ADOC modification Pattern C.​

Document 01:
![image](https://github.com/user-attachments/assets/01b76410-d26a-4953-a877-b0a0ca89bb91)

![image](https://github.com/user-attachments/assets/93ea184c-b833-447f-8d79-37b7f91abf99)

![image](https://github.com/user-attachments/assets/319889f9-4e4c-4f87-b8c5-e30e5740aeb3)

![image](https://github.com/user-attachments/assets/f98b365f-4c8f-4ec8-b850-36c1d13ce96f)

![image](https://github.com/user-attachments/assets/e2a7081b-aeda-4435-adb6-0be365d00751)

Document 02:
![image](https://github.com/metanorma/mn-samples-plateau/assets/55683568/d9077d46-ec28-4843-91f1-03abfda71641)

_32nd, 33rd, 35th, 36th, 38th and 56th comment from Plateau team_

**Comment by anermina** [comment]
Confirming the fix.

![image](https://github.com/user-attachments/assets/e2001d39-13d3-4654-be89-c45e00f59b7d)
![image](https://github.com/user-attachments/assets/e2363130-29a2-4c1f-8436-44c2a25b8554)
![image](https://github.com/user-attachments/assets/9612a151-8115-4c1b-be00-1487af72ae59)
![image](https://github.com/user-attachments/assets/e702e222-82d4-498a-9b64-d638ef9812f3)
![image](https://github.com/user-attachments/assets/4151a9dd-c359-46e0-96fe-0e3a37d84775)

**Comment by ronaldtse** [comment]
Fixed as per @anermina .
