### ISSUE TITLE
Document 02: Fix markup for the table cells

### ISSUE THREAD

**Issue by anermina** [metanorma/mn-samples-plateau#79]
Procedure: table is collapsed with cells overlaid → likely ADOC modification Pattern C.​

![image](https://github.com/metanorma/mn-samples-plateau/assets/55683568/12ff26a9-22f8-44bf-9be1-f8a4b33f8aaf)

_58th comment from Plateau team_

**Comment by anermina** [comment]
https://github.com/metanorma/mn-samples-plateau/pull/126/commits/31bfa9d0ddd83b1155fcab6c2f81728fe36a8535 fixes this issue.

![image](https://github.com/user-attachments/assets/9ad28d5b-e152-4a70-8967-e9512ddd3059)

**Comment by ronaldtse** [comment]
Fixed as per @anermina .
