### ISSUE TITLE
Document 02: Missing framework for requirements

### ISSUE THREAD

**Issue by anermina** [metanorma/mn-samples-plateau#82]
Procedure: no framework for requirements Numerous similar sections below → thought to be ADOC modifications Pattern C​

![image](https://github.com/metanorma/mn-samples-plateau/assets/55683568/dbd99b68-5d00-4528-b102-2fd983c0c941)

_61st comment from Plateau team_​

**Comment by ronaldtse** [comment]
Superseded and addressed by:
* https://github.com/metanorma/metanorma-plateau/issues/79
