### ISSUE TITLE
Document 02: Fix subclause numbering

### ISSUE THREAD

**Issue by anermina** [metanorma/mn-samples-plateau#83]
Procedure manual: different specification for sequential numbers (I think this is more visible as it is the same as the product specification) → Proposal to the urban bureau or Pattern A

![image](https://github.com/metanorma/mn-samples-plateau/assets/55683568/18f31ed2-b2cf-4ebf-bbf1-2409f5c4e2d2)

_62nd comment from Plateau team_

**Comment by ronaldtse** [comment]
Superseded and addressed by:
* https://github.com/metanorma/metanorma-plateau/issues/68
