### ISSUE TITLE
Document 01 & 02: Remove numbering duplication

### ISSUE THREAD

**Issue by anermina** [metanorma/mn-samples-plateau#84]
Document 01:
Specification: different numbering notation specifications.​

　→ It may be possible to use ADOC, but will it affect the template? Pattern B​

![image](https://github.com/user-attachments/assets/e7d1b70e-7de5-4ed9-a81f-3978f9b89f3c)

Document 02:
手順書：連番が2つ付いている。 Numerous similar sections below.​

　　→ ADOC modification may be possible, but will it affect the template Pattern B

![image](https://github.com/metanorma/mn-samples-plateau/assets/55683568/b9ee6257-e507-4e08-b688-bc289edfb7e2)

_14th and 63rd comment from Plateau team_

**Comment by ronaldtse** [comment]
Superseded and addressed by:
* https://github.com/metanorma/metanorma-plateau/issues/68
