### ISSUE TITLE
Document 01 & 02: Change position of annotations

### ISSUE THREAD

**Issue by anermina** [metanorma/mn-samples-plateau#85]
Procedure: different display position for annotations → ADOC modification may be possible, but will it affect the template Pattern B​

Specification: differently written annotations Table 4-25 Table 4-26 Table 4-27​

 　→ Can the template be used for this purpose? Pattern B​

Document 01:
![image](https://github.com/user-attachments/assets/13cda0c1-1f78-4175-bdfc-2f9a74db8c4f)

![image](https://github.com/user-attachments/assets/96d9f911-9221-4401-918d-1f76df1b9628)

![image](https://github.com/user-attachments/assets/d44dc92c-b169-4844-8fe1-4e9fd5abdaae)

![image](https://github.com/user-attachments/assets/00dfc8cd-8953-4735-902d-91b85b5d0aa2)

![image](https://github.com/user-attachments/assets/78bf8dec-4c33-437a-be89-69ca4a6e6702)

![image](https://github.com/user-attachments/assets/06bbabf2-a860-4d3e-9b91-41b680f7595d)

![image](https://github.com/user-attachments/assets/1161ba41-620a-4e1c-946d-ad306f14d0d0)

![image](https://github.com/user-attachments/assets/a39c1042-7cf5-4206-9cdb-b5935d7c936f)

Document 02:
![image](https://github.com/metanorma/mn-samples-plateau/assets/55683568/b98628ba-a3fb-4222-a574-49729e05b70a)

_12th, 13th, 21st-26th and 64th comment from Plateau team_

**Comment by ronaldtse** [comment]
Superseded and addressed by:
* https://github.com/metanorma/metanorma-plateau/issues/72
