### ISSUE TITLE
Document 01 & 02: Change order of references and revision history

### ISSUE THREAD

**Issue by anermina** [metanorma/mn-samples-plateau#88]
* [x] https://github.com/metanorma/metanorma-plateau/issues/54

Procedures: reversed order of references and revision history → likely ADOC amendment Pattern C​

Document 01:
![image](https://github.com/user-attachments/assets/7c957155-5ede-43eb-a486-32f33420181b)

Document 02:
![image](https://github.com/metanorma/mn-samples-plateau/assets/55683568/c29f84bd-1ea6-4d2b-8495-4b591a0e569a)

_40th and 67th comment from Plateau team_

**Comment by ronaldtse** [comment]
Done.
