### ISSUE TITLE
Document 02: Revision history is treated as annex

### ISSUE THREAD

**Issue by anermina** [metanorma/mn-samples-plateau#89]
Procedures: revision history is treated as annex.　→ Can this be addressed by ADOC amendment Pattern C.

![image](https://github.com/metanorma/mn-samples-plateau/assets/55683568/6391b087-231b-4c4e-ae0f-509f9c6b128c)

_68th comment from Plateau team_

Depends on:
* [x] https://github.com/metanorma/metanorma-plateau/issues/53

**Comment by ronaldtse** [comment]
Superseded and addressed in https://github.com/metanorma/metanorma-plateau/issues/70
