### ISSUE TITLE
Document 02: Index terms/glossary is missing

### ISSUE THREAD

**Issue by anermina** [metanorma/mn-samples-plateau#91]
Procedure: no index → ADOC modification thought to be an ADOC modification Pattern C

![image](https://github.com/metanorma/mn-samples-plateau/assets/55683568/8ce1a078-76bf-45e9-bd11-7bac4ed2e4f4)

_70th comment from Plateau team_

**Comment by ronaldtse** [comment]
@anermina any updates?

**Comment by anermina** [comment]
@ronaldtse sorry for the delay, I will try to finish this by the end of the day

**Comment by anermina** [comment]
Index section does not get generated in my environment, unless using the ISO flavor. I am currently double-checking this with Manuel.

**Comment by ronaldtse** [comment]
Then maybe it is a Plateau flavor issue. Let’s ping @opoudjis

**Comment by opoudjis** [comment]
Index generation was crashing because I had not provided a Japanese equivalent of "see" in metanorma-iso. Now that I have, 

````
== Clause 1

Hello ((hello))

== Clause 2
And ((goodbye,hello))

[index]
== 索引
````

is generating the following HTML:

![Screenshot 2024-08-21 at 22 23 48](https://github.com/user-attachments/assets/e04ccd6f-e11b-4f92-aa94-d6769990720f)

Please confirm that is doing what is expected.

**Comment by anermina** [comment]
Thanks @opoudjis !
I actually cannot generate an Index section using flavors such as JIS and OGC. 
However, this will help me check whether the indices and the Index section for this document are generated correctly.

**Comment by opoudjis** [comment]
I'm confused. All I can say is, try generating a document using the latest metanorma-iso and plateau, and with what I posed above as its body. I am getting the index when I put in 

````
[index]
== 索引
````
