### ISSUE TITLE
Document 02: Revision history is missing

### ISSUE THREAD

**Issue by anermina** [metanorma/mn-samples-plateau#95]
Specification: no revision history → ADOC may be able to support this Pattern C

![image](https://github.com/metanorma/mn-samples-plateau/assets/55683568/32ec5c8d-3ab5-48ee-be03-ca20c02da3fa)

_74th comment from Plateau team_

**Comment by ronaldtse** [comment]
As per PLATEAU team, we need to combine the two Revision history sections (preface and postface)

**Comment by ronaldtse** [comment]
This is fixed in #159.
