### ISSUE TITLE
Document 01: Fix cross-references

### ISSUE THREAD

**Issue by anermina** [metanorma/mn-samples-plateau#99]
Specification: incorrect text and links in citation → likely ADOC correction Pattern C​

![image](https://github.com/user-attachments/assets/7dc799ac-7e3e-4285-a2b1-fecef0355773)

_7th comment from Plateau team_

**Comment by ronaldtse** [comment]
Superseded and addressed by:
* https://github.com/metanorma/metanorma-plateau/issues/76
